//===- ScheduleGen.cpp - Generate Transform-dialect schedules -------------===//
//
// The schedule is produced as text on purpose: it is the same artifact a user
// checks in under schedules/ and edits by hand, so there is one format for
// generated and hand-tuned schedules.
//
//===----------------------------------------------------------------------===//

#include "nanodsp/Schedule/ScheduleGen.h"
#include "nanodsp/Schedule/TileSizeModel.h"

#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/raw_ostream.h"

using namespace mlir;
using namespace mlir::nanodsp;

SmallVector<linalg::GenericOp>
mlir::nanodsp::tagScheduleTargets(Operation *root) {
  SmallVector<linalg::GenericOp> ops;
  root->walk([&](linalg::GenericOp op) {
    op->setAttr(
        kScheduleTagAttr,
        StringAttr::get(op.getContext(), "op" + std::to_string(ops.size())));
    ops.push_back(op);
  });
  return ops;
}

void mlir::nanodsp::stripScheduleTags(Operation *root) {
  root->walk([](linalg::GenericOp op) { op->removeAttr(kScheduleTagAttr); });
}

static std::string joinSizes(ArrayRef<int64_t> sizes) {
  std::string s;
  llvm::raw_string_ostream os(s);
  os << "[";
  llvm::interleaveComma(sizes, os);
  os << "]";
  return s;
}

/// Emits one tile_using_for and returns the handle to the tiled op. A size of
/// 0 leaves that loop untiled; with no non-zero size nothing is emitted.
/// `innermostLoop` is updated to the handle of the innermost generated loop.
static std::string emitTile(llvm::raw_ostream &os, StringRef handle,
                            StringRef name, ArrayRef<int64_t> sizes,
                            std::string &innermostLoop) {
  unsigned numLoops = llvm::count_if(sizes, [](int64_t s) { return s != 0; });
  if (numLoops == 0)
    return handle.str();
  innermostLoop = llvm::formatv("{0}_loops#{1}", name, numLoops - 1).str();
  std::string types = "!transform.any_op";
  for (unsigned i = 0; i < numLoops; ++i)
    types += ", !transform.any_op";
  os << llvm::formatv("    %{0}, %{0}_loops:{1} = "
                      "transform.structured.tile_using_for %{2} tile_sizes "
                      "{3} : (!transform.any_op) -> ({4})\n",
                      name, numLoops, handle, joinSizes(sizes), types);
  return name.str();
}

std::string mlir::nanodsp::buildDefaultSchedule(ArrayRef<linalg::GenericOp> ops,
                                                const TargetModel &target) {
  std::string text;
  llvm::raw_string_ostream os(text);
  os << "// Generated by -nanodsp-emit-schedule{target=" << target.name
     << "}.\n"
     << "module attributes {transform.with_named_sequence} {\n"
     << "  transform.named_sequence @__transform_main("
        "%root: !transform.any_op {transform.readonly}) {\n";

  // Ops vectorized after unit-dim folding: (tag, innermost loop handle).
  SmallVector<std::pair<std::string, std::string>> deferred;
  for (linalg::GenericOp op : ops) {
    auto tag = op->getAttrOfType<StringAttr>(kScheduleTagAttr).getValue();
    FailureOr<TileSizes> sizes = computeTileSizes(op, target);
    if (failed(sizes)) {
      os << "    // " << tag << ": not handled by the tile-size model\n";
      continue;
    }

    // tile_using_for sizes are relative to the op being tiled, and 0 means
    // "do not tile this loop".
    SmallVector<int64_t> cacheSizes, regSizes;
    for (auto [range, cache, reg] :
         llvm::zip_equal(sizes->loopRanges, sizes->cache, sizes->reg)) {
      cacheSizes.push_back(cache == range ? 0 : cache);
      regSizes.push_back(reg == cache ? 0 : reg);
    }

    os << llvm::formatv("    // {0}: loops {1}, cache tile {2} ({3} bytes), "
                        "register tile {4}\n",
                        tag, joinSizes(sizes->loopRanges),
                        joinSizes(sizes->cache), sizes->cacheWorkingSetBytes,
                        joinSizes(sizes->reg));
    os << llvm::formatv(
        "    %{0} = transform.structured.match ops{{[\"linalg.generic\"]} "
        "attributes {{{1} = \"{0}\"} in %root : (!transform.any_op) -> "
        "!transform.any_op\n",
        tag, kScheduleTagAttr);
    std::string innermostLoop;
    std::string handle =
        emitTile(os, tag, (tag + "_cache").str(), cacheSizes, innermostLoop);
    handle =
        emitTile(os, handle, (tag + "_reg").str(), regSizes, innermostLoop);

    // Register tiles are vectorized only after their unit dims are folded
    // away (below, for all ops at once):
    //  * a matmul tile is m x n x 1; vectorized as is, the trailing unit
    //    dim survives as vector<4x16x1xf32>, which LLVM lowers to scalar
    //    multiplies. Folded, it is a clean 2-D multiply-add.
    //  * a conv's input map (oh + kh, ow + kw) is not a projected
    //    permutation, which the vectorizer rejects, until kh and kw are gone.
    // An op that got no loops has no unit dims to fold and no loop to find
    // it through afterwards, so it is vectorized right away if it can be.
    bool projectedPermutations =
        llvm::all_of(op.getIndexingMapsArray(), [](AffineMap map) {
          return map.isProjectedPermutation();
        });
    if (!innermostLoop.empty()) {
      deferred.push_back({tag.str(), innermostLoop});
    } else if (projectedPermutations) {
      os << "    transform.structured.vectorize %" << handle
         << " : !transform.any_op\n";
    } else {
      os << "    // " << tag << ": untiled, left scalar\n";
    }
  }

  os << "    %funcs = transform.structured.match ops{[\"func.func\"]} in "
        "%root : (!transform.any_op) -> !transform.any_op\n";
  if (!deferred.empty()) {
    // Folding rewrites the ops (and drops their tags), so they are found
    // again through the innermost loop of their register tile.
    os << "    transform.apply_patterns to %funcs {\n"
       << "      transform.apply_patterns.linalg."
          "fold_unit_extent_dims_via_slices\n"
       << "      transform.apply_patterns.canonicalization\n"
       << "    } : !transform.any_op\n";
    for (auto &[tag, loop] : deferred) {
      os << llvm::formatv("    %{0}_folded = transform.structured.match "
                          "ops{{[\"linalg.generic\"]} in %{1} : "
                          "(!transform.any_op) -> !transform.any_op\n",
                          tag, loop);
      os << "    transform.structured.vectorize %" << tag
         << "_folded : !transform.any_op\n";
    }
  }
  os << "    transform.apply_patterns to %funcs {\n"
     << "      transform.apply_patterns.canonicalization\n"
     << "    } : !transform.any_op\n"
     << "    transform.yield\n"
     << "  }\n"
     << "}\n";
  return text;
}
